### ISSUE TITLE
writestr method creates empty file

### ISSUE THREAD

**Issue by helelily** [danifus/pyzipper#11]
```python
import pandas
import pyzipper

data = [[1,2],[3,4], [5,6]]
data = pandas.DataFrame(data)
data.columns = ['one','two']

pw = 'testing'

with pyzipper.AESZipFile('ziptest.zip','w',
                         encryption=pyzipper.WZ_AES) as zf:
    zf.setpassword(pw.encode('utf-8'))
    zf.writestr('test.csv',data.to_csv())

```

This snippet successfully creates a protected archive but the file it writes to is empty, seems like something is happening in the writestr method?

For context I'm on a mac and python is version 3.7.4

**Comment by danifus** [comment]
Hi,

I've confirmed that `writestr` is working for me for both `str` and `bytes` content. Can you confirm that `data.to_csv()` is returning content to be written?

Thanks,
Dan

**Comment by helelily** [comment]
Hi, I'm realizing now it does work programmatically, the main thing was that the extraction utility I was using on my mac was not compatible.  I had to find a different utility to open it as an end user - I guess that is expected behavior?

**Comment by danifus** [comment]
Yeah, that's expected behaviour. AES protected zips aren't supported by all zip utilities (most that come with the OS don't support it).

Glad to hear you got it working :)
