### ISSUE TITLE
Bad HMAC check for file with LZMA/AES

### ISSUE THREAD

**Issue by MatthewWalker** [danifus/pyzipper#15]
Firstly, thanks for this library, we've found it very useful :).

We're encountering an issue with a small number of LZMA compressed / AES encrypted zips where pyzipper is complaining that the HMAC mismatches.

It can be reproduced with the code in [this Gist](https://gist.github.com/MatthewWalker/72d5230d7a784edc5f9fbe10b301a4c5).

There seems to be some padding at the end of the compressed stream which is not being read by ZipExtFile._read1() after the decompressor says that it is at EOF. This causes the HMAC to mismatch as it wasn't fed the last few bytes.

There are a couple of changes that can make it work, but I'm not sure how solid they are:
* Only call self.check_integrity() in _read1() if self._compress_left <= 0. This would end up not checking the integrity for these files.
* Change the `if self._left <= 0:` check in _read1() to be `if self._left <=0 and self._compress_left <= 0:`. I'm not sure what the consequences of this change are.
* Add a special case for `if self._compress_type == ZIP_LZMA:` which reads any remaining bytes when the decompressor is at EOF.

**Comment by danifus** [comment]
Thanks for the bug report! I've been pretty busy and what to check if this has any implications for zip bombs (ensuring we don't read past the number of bytes reported in the zip header protects us from it exploding into gigabytes). I'll check it out and release an updated version in a couple of days.

**Comment by danifus** [comment]
Hi, I've pushed a new version of pyzipper with a fix for this issue. I took a slightly different approach but it essentially does the same thing. Try running the new version and see if it fixes the bug you were seeing.

Thanks for the report and patch!
