### ISSUE TITLE
Upstream to official python stdlib

### ISSUE THREAD

**Issue by JuniorJPDJ** [danifus/pyzipper#17]
Hi!
What do you think about upstreaming your fork?
It would be cool to have it included in stdlib!

**Comment by danifus** [comment]
Hi, I tried merging the refactor code in a single pr comprised of isolated commits but I think the size of the PR scared people off: https://bugs.python.org/issue37538

From there I started making PRs for isolated changes but I haven't had time to focus on it for a while. The changes that I've been upstreaming have focused on changes making the classes in the zipfile module easily subclassable and extensible. For various reasons, I don't think the crypto parts of this repo would be merged into stdlib (eg. https://bugs.python.org/issue9170)

**Comment by JuniorJPDJ** [comment]
Not including crypto into stdlib is pretty sad but it makes sense.

Keep your good work! I close this as you are already trying to upstream as much as you can :D
