### ISSUE TITLE
Opening encrypted zip files on Catalina MacOSX

### ISSUE THREAD

**Issue by jjtapia** [danifus/pyzipper#18]
Hello, I am having issues opening files encrypted with pyzipper using the native Archive utility app from MacOSX

When using ZIP_BZIP2 or ZIP_LZMA archiver will fail with error 79

![image](https://user-images.githubusercontent.com/4514041/118940826-ba3e5b80-b916-11eb-8d8a-e9d9a56b46c4.png)

When using ZIP_DEFLATED archiver will fail to accept the provided password

The zip file will open, accept the password and uncompress correctly though when using ZIP_STORED

macosx version: 10.15
pyzipper version :0.3.5 (from pypi)

The file will open correctly when using 7z though, so I'm guessing it is some kind of incompatibility with the native app

**Comment by danifus** [comment]
Hi,

I'm not using that version of mac osx so I can't test it but I'm surprised that it worked with ZIP_STORED and not ZIP_DEFLATED. I haven't tested it on catalina but these AES encrypted files were unable to be opened by the native mac archiver when I last tested. Are you able to share the script you used to generate the files?

For lzma and bzip2, I think you are correct that this is an issue with the native app - I get similar errors when using Python's zipfile module.

**Comment by jjtapia** [comment]
Sure, here is the script

```Python
zf = pyzipper.AESZipFile('test_def.zip', mode="w", compression=pyzipper.ZIP_DEFLATED, encryption=pyzipper.WZ_AES)
zf.setpassword(b'cg')
zf.writestr('test.txt', 'hello world')
zf.close()

zf = pyzipper.AESZipFile('test_store.zip', mode="w", compression=pyzipper.ZIP_STORED, encryption=pyzipper.WZ_AES)
zf.setpassword(b'cg')
zf.writestr('test.txt', 'hello world')
zf.close()
```

**Comment by danifus** [comment]
Thanks for the script. I've found a Catalina mac to test and am seeing the same behaviour but the file extracted from the ZIP_STORED file is empty. Is there contents in your file extracted from the ZIP_STORED archive?

**Comment by danifus** [comment]
I found a github issue for Keka (mac archiving program) that suggests the AES encryption isn't supported by the native mac archiver: https://github.com/aonez/Keka/issues/477

I think this is a short coming of the native mac archiver program. Thanks for raising the issue and doing some testing for me though :)

**Comment by jjtapia** [comment]
Thank you for following up. I went back to the extracted file from the encrypted archive and after checking the contents it seems its just junk code rather than the original contents like the inforamtion you found suggests. Like you say this seems to be a shortcoming of the archiver program, which is a shame. Going through the code it does not seem the library supports CRC Encryption, so I guess I should look for an alternative if I want my pipeline to support MacOSX clients.
