### ISSUE TITLE
Error Extracting Files

### ISSUE THREAD

**Issue by ConorBreen959** [danifus/pyzipper#19]
Hi,

I'm trying to create an encrypted zip file that will be opened by several users on Windows and Linux. However, the zip cannot be extracted by the default archive manager on either Windows or Linux. I'm just using the pyzipper example code for now:

```
secret_password = b'test123'

with pyzipper.AESZipFile('new_test.zip',
                          'w',
                          compression=pyzipper.ZIP_DEFLATED,
                          encryption=pyzipper.WZ_AES) as zf:
     zf.pwd = secret_password
     zf.writestr('test.txt', "What ever you do, don't tell anyone!")
```

**Comment by danifus** [comment]
Hi,

pyzipper creates an archive using the winzip AES standard. Unfortunately the default archive managers on Windows, Mac and Linux can not decrypt these files.

The 'traditional' zip encryption can be processed by default archive managers but is considered insecure: https://en.wikipedia.org/wiki/ZIP_(file_format)#Encryption  If you want to investigate that option further here is a package I found that provides this functionality: https://github.com/devthat/zipencrypt (I haven't used this package before)
