### ISSUE TITLE
Error running pyzipper in Lambda function

### ISSUE THREAD

**Issue by NMuee** [danifus/pyzipper#23]
Hi Team, 

I am trying to encrypt a zip file in a lambda. 
I managed to attached pyzipper library as a layer in lambda.
However when I run my script I encounter this error. 
May I know how this can be fixed? 
Thank you.

`"errorMessage": "Cannot load native module 'Cryptodome.Hash._SHA1': Not found '_SHA1.cpython-39-x86_64-linux-gnu.so', Cannot load '_SHA1.abi3.so': /var/task/Cryptodome/Util/../Hash/_SHA1.abi3.so: invalid ELF header, Not found '_SHA1.so'",
  "errorType": "OSError"`

My code used:
`with pyzipper.AESZipFile(ouput_file, 'w',encryption=pyzipper.WZ_AES) as zf:
        zf.setpassword(b'password')
        zf.write(input_file, arcname=input_file)`

**Comment by danifus** [comment]
Hi,

I think this is possibly an issue with the way the your lambda package is being built: https://github.com/Legrandin/pycryptodome/issues/69#issuecomment-558039360
