### ISSUE TITLE
Unable to use PyZipper on AWS Lambda

### ISSUE THREAD

**Issue by jevng** [danifus/pyzipper#26]
Hello,,

I am facing an issue where I am unable to import pyzipper in aws lambda due to the following error.

[ERROR] OSError: Cannot load native module 'Cryptodome.Hash._SHA1': Not found '_SHA1.cpython-37m-x86_64-linux-gnu.so', Not found '_SHA1.abi3.so', Not found '_SHA1.so'

Has anyone faced this issue before when using pyzipper through an AWS layer?

Thanks!

**Comment by danifus** [comment]
Hi,

Yes, other people have reported this. https://github.com/danifus/pyzipper/issues/23 should help you resolve this.

Thanks,
Dan
