### ISSUE TITLE
Execution error, module found but attributes are not found

### ISSUE THREAD

**Issue by DRVR1** [danifus/pyzipper#29]
windows console:
```
pip  install pyzipper
Requirement already satisfied: pyzipper in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (0.3.6)
```

code used:
```
import pyzipper

secret_password = b'lost art of keeping a secret'

with pyzipper.AESZipFile('new_test.zip',
                         'w',
                         compression=pyzipper.ZIP_LZMA,
                         encryption=pyzipper.WZ_AES) as zf:
    zf.setpassword(secret_password)
    zf.writestr('test.txt', "What ever you do, don't tell anyone!")

with pyzipper.AESZipFile('new_test.zip') as zf:
    zf.setpassword(secret_password)
    my_secrets = zf.read('test.txt')
```
at execution:
`AttributeError: partially initialized module 'pyzipper' has no attribute 'AESZipFile' (most likely due to a circular import)`

hint: windows 11, python 3.10.9.

**Comment by danifus** [comment]
Hi,

I wasn't able to reproduce this. Can you check if this is the issue you're encountering: https://stackoverflow.com/questions/59762996/how-to-fix-attributeerror-partially-initialized-module

Thanks

**Comment by DRVR1** [comment]
My file was called pyzipper.py , i changed its name and now it worked! Thank you
