### ISSUE TITLE
Encrypt filenames

### ISSUE THREAD

**Issue by tommyzat** [danifus/pyzipper#7]
It would be a great addition if filenames in the zip file could also be encrypted/obfuscated.

**Comment by danifus** [comment]
Yeah, that is a short coming of the winzip AES encryption scheme. I created this project for compatibility with encrypted winzip files as I see them semi-regularly in the wild.

The problem with rolling our own scheme for hiding filenames is that no one else would be using our scheme, so we would only be talking to other people who use this library. Also, creating a scheme that is secure is not easy to get properly correct. If there was a commonly used format that offered this (and I had enough time), I would look at it (or preferably accept a patch).

A workaround would be to obfuscate the filenames in your application code or create a normal zip file and encrypt the entire file (there are a few python libraries that can encrypt entire files but I haven't evaluated any of them).

**Comment by lclevy** [comment]
If you want info on 7zip format and filenames encryption https://github.com/lclevy/unarcrypto

**Comment by danifus** [comment]
Thanks for the link @lclevy. That's an interesting repo! Perhaps sometime in the future I'll get around to adding support for 7z :)

**Comment by lclevy** [comment]
https://pypi.org/project/py7zr/
