### ISSUE TITLE
Avoid adding directories to encrypted zip

### ISSUE THREAD

**Issue by blueteamzone** [danifus/pyzipper#8]
I have got a list of file paths and I wanted to create an encrypted zip file using them.
```python
>>> import pyzipper
>>> with pyzipper.AESZipFile('test.zip' ,'a') as zf:
...     zf.pwd = b'test'
...     for f_path in listfiles:
...         zf.write(f_path)
``` 
The above code creates the encrypted zip file, however it also creates the directories. For example when I extract the content of the zip.
```
/home/bob/files/testfile_1.csv
/home/bob/files/testfile_2.csv
/home/bob/files/testfile_3.csv
```
How can I avoid this? I want to find only the files testfile_1.csv, testfile_2.csv, testfile_3.csv when I extract the zip.

**Comment by danifus** [comment]
The solution to this is the same as the using Python's `zipfile` module [`ZipFile.write`](https://docs.python.org/3.7/library/zipfile.html#zipfile.ZipFile.write)

You can get the results you want by specifying the name you would like the file to have in the archive (here I'm using `os.path.basename()` to get the last part, the filename in your example, from the full path):

`zf.write(f_path, arcname=os.path.basename(f_path))`
